const identityFields = [
  {
    label: 'Nama Sekolah',
    name: 'name',
    render: null,
    require: true,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'NPSN',
    name: 'npsn',
    render: null,
    require: true,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'NSS',
    name: 'nss',
    render: null,
    require: true,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Alamat',
    name: 'address',
    render: null,
    require: true,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Kode Pos',
    name: 'postalCode',
    render: null,
    require: false,
    type: 'number',
    inputItems: null,
  },
  {
    label: 'No. HP',
    name: 'phone',
    render: null,
    require: false,
    type: 'number',
    inputItems: null,
  },
  {
    label: 'Kelurahan',
    name: 'kelurahan',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Kecamatan',
    name: 'kecamatan',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Kabupaten',
    name: 'kabupaten',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Provinsi',
    name: 'province',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Website',
    name: 'website',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
  {
    label: 'Email',
    name: 'email',
    render: null,
    require: false,
    type: 'input',
    inputItems: null,
  },
]
export default identityFields
