const parentFields = [
  {
    label: 'Data Ayah',
    name: 'titleform',
  },
  {
    label: 'Nama Ayah',
    name: 'fatherName',
    require: true,
    type: 'input',
  },
  {
    label: 'Tahun Lahir',
    name: 'fatherBirthYear',
    require: false,
    type: 'input',
  },
  {
    label: 'Pendidikan',
    name: 'fatherLastEducation',
    require: false,
    type: 'input',
  },
  {
    label: 'Penghasilan',
    name: 'fatherIncome',
    require: false,
    type: 'input',
  },
  {
    label: 'Kebutuhan Khusus',
    name: 'fatherOccupation',
    require: false,
    type: 'input',
  },
  {
    label: 'No. HP',
    name: 'fatherPhone',
    require: false,
    type: 'number',
    controlNumber: false,
  },
  {
    label: 'Data Ibu',
    name: 'titleform',
  },
  {
    label: 'Nama Ibu',
    name: 'motherName',
    require: true,
    type: 'input',
  },
  {
    label: 'Tahun Lahir',
    name: 'motherBirthYear',
    require: false,
    type: 'input',
  },
  {
    label: 'Pendidikan',
    name: 'motherLastEducation',
    require: false,
    type: 'input',
  },
  {
    label: 'Penghasilan',
    name: 'motherIncome',
    require: false,
    type: 'input',
  },
  {
    label: 'Kebutuhan Khusus',
    name: 'motherOccupation',
    require: false,
    type: 'input',
  },
  {
    label: 'No. HP',
    name: 'motherPhone',
    require: false,
    type: 'number',
    controlNumber: false,
  },
  {
    label: 'Data Wali',
    name: 'titleform',
  },
  {
    label: 'Nama Wali',
    name: 'guardName',
    require: false,
    type: 'input',
  },
  {
    label: 'Tahun Lahir',
    name: 'guardBirthYear',
    require: false,
    type: 'input',
  },
  {
    label: 'Pendidikan',
    name: 'guardLastEducation',
    require: false,
    type: 'input',
  },
  {
    label: 'Penghasilan',
    name: 'guardIncome',
    require: false,
    type: 'input',
  },
  {
    label: 'Kebutuhan Khusus',
    name: 'guardOccupation',
    require: false,
    type: 'input',
  },
  {
    label: 'No. HP',
    name: 'guardPhone',
    require: false,
    type: 'number',
    controlNumber: false,
  },
]
export default parentFields
