const navRoute = [
  {
    icon: <i className="ri-dashboard-line"></i>,
    label: 'Dashboard',
    href: '/',
    children: null,
  },
  {
    icon: <i className="ri-school-line"></i>,
    label: 'Master',
    href: null,
    children: [
      {
        icon: null,
        label: 'Identitas Sekolah',
        title: 'Identitas Sekolah',
        href: '/master/identitas-sekolah',
        children: null,
      },
      {
        icon: null,
        label: 'Kurikulum',
        title: 'Data Kurikulum',
        href: '/master/kurikulum',
        children: null,
      },
      {
        icon: null,
        label: 'Tahun Akademik',
        title: 'Tahun Akademik',
        href: '/master/tahun-akademik',
        children: null,
      },
      {
        icon: null,
        label: 'Gedung',
        title: 'Data Gedung',
        href: '/master/gedung',
        children: null,
      },
      {
        icon: null,
        label: 'Ruangan',
        title: 'Data Ruangan',
        href: '/master/ruangan',
        children: null,
      },
      {
        icon: null,
        label: 'Unit',
        title: 'Data Unit',
        href: '/master/unit',
        children: null,
      },
      {
        icon: null,
        label: 'Jurusan',
        title: 'Data Jurusan',
        href: '/master/jurusan',
        children: null,
      },
      {
        icon: null,
        label: 'Ruang Kelas',
        title: 'Data Ruang Kelas',
        href: '/master/ruang-kelas',
        children: null,
      },
      {
        icon: null,
        label: 'Golongan',
        title: 'Data Golongan',
        href: '/master/golongan',
        children: null,
      },
      {
        icon: null,
        label: 'Jenis PTK',
        title: 'Data Jenis PTK',
        href: '/master/jenis-ptk',
        children: null,
      },
      {
        icon: null,
        label: 'Jabatan',
        title: 'Data Jabatan',
        href: '/master/jabatan',
        children: null,
      },
      {
        icon: null,
        label: 'Status Pegawai',
        title: 'Data Status Pegawai',
        href: '/master/status-pegawai',
        children: null,
      },
    ],
  },
  {
    icon: <i className="ri-group-line"></i>,
    label: 'Pengguna',
    href: null,
    children: [
      {
        icon: null,
        label: 'Siswa',
        title: 'User Siswa',
        href: '/pengguna/siswa',
        children: null,
      },
      {
        icon: null,
        label: 'Pegawai',
        title: 'User Pegawai',
        href: '/pengguna/pegawai',
        children: null,
      },
    ],
  },
  {
    icon: <i className="ri-graduation-cap-line"></i>,
    label: 'Akademik',
    href: null,
    children: [
      {
        icon: null,
        label: 'Kelompok Mata Pelajaran',
        title: 'Kelompok Mata Pelajaran',
        href: '/akademik/kelompok-mata-pelajaran',
        children: null,
      },
      {
        icon: null,
        label: 'Mata Pelajaran',
        title: 'Mata Pelajaran',
        href: '/akademik/mata-pelajaran',
        children: null,
      },
      {
        icon: null,
        label: 'Jadwal Pelajaran',
        title: 'Jadwal Pelajaran',
        href: '/akademik/jadwal-pelajaran',
        children: null,
      },
      {
        icon: null,
        label: 'Rentang Nilai',
        title: 'Rentang Nilai',
        href: '/akademik/rentang-nilai',
        children: null,
      },
    ],
  },
  {
    icon: <i className="ri-list-check-3"></i>,
    label: 'Absensi dan Penilaian',
    href: null,
    children: [
      {
        icon: null,
        label: 'Absensi Siswa',
        title: 'Absensi Siswa',
        href: '/absensi/siswa',
        children: null,
      },
      {
        icon: null,
        label: 'Absensi Pegawai',
        title: 'Absensi Pegawai',
        href: '/absensi/pegawai',
        children: null,
      },
      {
        icon: null,
        label: 'Penilaian Siswa',
        title: 'Penilaian Siswa',
        href: '/penilaian/siswa',
        children: null,
      },
    ],
  },
  {
    icon: <i className="ri-box-3-line"></i>,
    label: 'Inventaris',
    href: '/inventaris',
    children: null,
  },
  {
    icon: <i className="ri-wallet-line"></i>,
    label: 'Keuangan',
    href: null,
    children: [
      {
        icon: null,
        label: 'Pembayaran Siswa',
        title: 'Pembayaran Siswa',
        href: '/keuangan/pembayaran-siswa',
        children: null,
      },
      {
        icon: null,
        label: 'Pengaturan Pembayaran',
        title: 'Pengaturan Pembayaran',
        href: null,
        children: [
          {
            icon: null,
            label: 'Akun Biaya',
            title: 'Akun Biaya',
            href: '/keuangan/akun-biaya',
            children: null,
          },
          {
            icon: null,
            label: 'Pos Bayar',
            title: 'Pos Bayar',
            href: '/keuangan/pos-bayar',
            children: null,
          },
          {
            icon: null,
            label: 'Unit Pos',
            title: 'Unit Pos',
            href: '/keuangan/unit-pos',
            children: null,
          },
        ],
      },
      {
        icon: null,
        label: 'Kas & Bank',
        title: 'Kas & Bank',
        href: null,
        children: [
          {
            icon: null,
            label: 'Saldo Awal',
            title: 'Saldo Awal',
            href: '/keuangan/saldo-awal',
            children: null,
          },
          {
            icon: null,
            label: 'Kas Keluar',
            title: 'Kas Keluar',
            href: '/keuangan/kas-keluar',
            children: null,
          },
          {
            icon: null,
            label: 'Kas Masuk',
            title: 'Kas Masuk',
            href: '/keuangan/kas-masuk',
            children: null,
          },
        ],
      },
    ],
  },
  {
    icon: <i className="ri-file-chart-line"></i>,
    label: 'Laporan',
    href: null,
    children: [
      {
        icon: null,
        label: 'Presensi Siswa',
        title: 'Laporan Presensi Siswa',
        href: '/laporan/presensi-siswa',
        children: null,
      },
      {
        icon: null,
        label: 'Presensi Pegawai',
        title: 'Laporan Presensi Pegawai',
        href: '/laporan/presensi-pegawai',
        children: null,
      },
      {
        icon: null,
        label: 'Pembayaran',
        title: 'Laporan Pembayaran',
        href: '/laporan/pembayaran',
        children: null,
      },
      {
        icon: null,
        label: 'Keuangan',
        title: 'Laporan Keuangan',
        href: '/laporan/keuangan',
        children: null,
      },
      {
        icon: null,
        label: 'Nilai',
        title: 'Nilai Siswa',
        href: '/laporan/nilai',
        children: null,
      },
    ],
  },
]

export default navRoute
